services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./task:/var/www/html/
    networks:
      - backend
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./task:/var/www/html/
    networks:
      - backend
    depends_on:
        mysql:
          condition: service_healthy

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cssoft
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 2s
      interval: 2s
      timeout: 2s
      retries: 100
    volumes:
      - mysql:/var/lib/mysql
      - './.docker/mysql/:/docker-entrypoint-initdb.d/'
    # ports:        # only for development
    #   - 3306:3306 #
    networks:
      - backend
volumes:
  mysql:
networks:
  backend:
